# -*- coding: utf-8 -*-
"""Digital Clock Using python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Pi61ne07hqK8NxOfPEptYJ5JREZY2er7
"""

# Name:Chinmay Sanjay Rane

# Task 3: Digital Clock Using python

from tkinter import Label, Tk 

import time

app_window = Tk() 
app_window.title("Digital Clock") 
app_window.geometry("420x150") 
app_window.resizable(1,1)

text_font= ("Boulder", 68, 'bold')
background = "#f2e750"
foreground= "#363529"
border_width = 25

label = Label(app_window, font=text_font, bg=background, fg=foreground, bd=border_width) 
label.grid(row=0, column=1)

def digital_clock(): 
   time_live = time.strftime("%H:%M:%S")
   label.config(text=time_live) 
   label.after(200, digital_clock)

digital_clock()
app_window.mainloop()